### ISSUE TITLE
Somewhat broken on the store page

### ISSUE THREAD

**Issue by MoneyAllDay** [pabli24/GOG-Dark#11]
The theme became a bit broken on the [store page](https://www.gog.com/games).

![screenshot 2021-12-05 01 54 21](https://user-images.githubusercontent.com/19583547/144730496-2bc8c135-bbae-4939-9eeb-27d00f9dfa52.png)

**Comment by pabli24** [comment]
Fixed by copying the body.dark-theme css that gog com has in their code but you can't enable it :D 
Maybe someday they will finally add the official dark mode
