### ISSUE TITLE
CSS formatting

### ISSUE THREAD

**Issue by ColonelGerdauf** [pabli24/GOG-Dark#40]
Two main things, and they are cited by Stylus as errors:

1) in CSS, you cannot create a variable the same way as you typically would in other languages.
2) with declarations, it is recommended to append a semicolon at the end. In fact, it is required when you are writing more than one declaration per defined selector or group of selectors.

**Comment by pabli24** [comment]
The style uses [Stylus preprocessor ](https://stylus-lang.com/)
